package:
  name: Pillow
  version: 8.0.1

source:
  url: https://files.pythonhosted.org/packages/2b/06/93bf1626ef36815010e971a5ce90f49919d84ab5d2fa310329f843a74bc1/Pillow-8.0.1.tar.gz
  sha256: 11c5c6e9b02c9dac08af04f093eb5a2f84857df70a7d4a6a6ad461aca803fb9e

  patches:
    - patches/disable_dependecies.patch

build:
  cflags: |
    -s USE_FREETYPE=1
    -s USE_LIBPNG=1
    -s USE_ZLIB=1
    -s USE_LIBJPEG=1
    -L../../../zlib/zlib-1.2.11/include
    -Wno-implicit-function-declaration
  ldflags: |
    ../../../../emsdk/emsdk/.emscripten_cache/asmjs/libpng.bc
    -L../../../../emsdk/emsdk/.emscripten_cache/asmjs/
    -L../../../zlib/zlib-1.2.11/lib/

# requirements:
#   run:
#     - zlib

test:
  imports:
    - Pillow

