package:
  name: Pillow
  version: 7.2.0

source:
  url: https://files.pythonhosted.org/packages/3e/02/b09732ca4b14405ff159c470a612979acfc6e8645dc32f83ea0129709f7a/Pillow-7.2.0.tar.gz
  sha256: 97f9e7953a77d5a70f49b9a48da7776dc51e9b738151b22dacf101641594a626

  patches:
    - patches/disable_dependecies.patch

build:
  cflags: -s USE_FREETYPE=1 -s USE_LIBPNG=1 -s USE_ZLIB=1 -s USE_LIBJPEG=1
  ldflags: ../../../../emsdk/emsdk/.emscripten_cache/asmjs/libpng.bc
  # post: |
  #   wget -O $SITEPACKAGES/matplotlib/mpl-data/fonts/ttf/Humor-Sans.ttf http://antiyawn.com/uploads/Humor-Sans-1.0.ttf
  #   rm -rf $SITEPACKAGES/matplotlib/backends/qt_editor
  #   rm -rf $SITEPACKAGES/matplotlib/backends/web_backend
  #   rm -rf $SITEPACKAGES/sphinxext
  #   cp $PKGDIR/src/fontList.json $SITEPACKAGES/matplotlib

# requirements:
#   run:
#     - zlib

test:
  imports:
    - Pillow

